name: Ping Backend Server

on:
    schedule:
        - cron: '*/5 * * * *'
jobs:
    ping-server:
        runs-on: ubuntu-latest
        steps:
            - name: 'Ping Server'
              run : curl https://backend-chronicle.onrender.com/health
